require 'colorize'

################################################################################
# deploy the hooks

namespace :deploy do

  desc "Deploy the LabNotebook2016_2017 deployment script"
  task :LabNotebook2016_2017 do
    puts "Deploying LabNotebook2016_2017 deployment script".green
    sh 'rsync post-receive_LabNotebook2016_2017 sensei@timc-bcm-15.imag.fr:/home/sensei/LabNotebook2016_2017.git/hooks/post-receive'
  end

end
